backend:
  name: github
  repo: jordanjamesmedia/partipoodles
  branch: main # Branch to update (optional; defaults to main)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "puppies" # Used in routes, e.g., /admin/collections/blog
    label: "Available Puppies" # Used in the UI
    folder: "_data/puppies" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Puppy Name", name: "name", widget: "string"}
      - {label: "Status", name: "status", widget: "select", options: ["available", "reserved", "sold"]}
      - {label: "Gender", name: "gender", widget: "select", options: ["male", "female"]}
      - {label: "Color", name: "color", widget: "string"}
      - {label: "Date of Birth", name: "birth_date", widget: "date"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Weight (current)", name: "weight", widget: "string"}
      - {label: "Expected Adult Weight", name: "expected_weight", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Health Testing", name: "health", widget: "text"}
      - {label: "Temperament", name: "temperament", widget: "text"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - label: "Photo Gallery"
        name: "gallery"
        widget: "list"
        field: {label: "Image", name: "image", widget: "image"}
      - {label: "Show on Homepage", name: "featured", widget: "boolean", default: false}
      - {label: "Available", name: "available", widget: "boolean", default: true}

  - name: "gallery" # Used in routes
    label: "Photo Gallery" # Used in the UI
    folder: "_data/gallery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document
      - {label: "Album Title", name: "title", widget: "string"}
      - {label: "Album Description", name: "description", widget: "text", required: false}
      - {label: "Category", name: "category", widget: "select", options: ["puppies", "adults", "facilities", "other"]}
      - {label: "Cover Image", name: "cover_image", widget: "image"}
      - label: "Photos"
        name: "photos"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      - {label: "Featured Album", name: "featured", widget: "boolean", default: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}

  - name: "settings"
    label: "Website Settings"
    files:
      - label: "Site Settings"
        name: "site"
        file: "_data/settings/site.yml"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Phone Number", name: "phone", widget: "string"}
          - {label: "Address", name: "address", widget: "text"}
          - {label: "Social Media Links", name: "social", widget: "object", fields: [
              {label: "Facebook", name: "facebook", widget: "string", required: false},
              {label: "Instagram", name: "instagram", widget: "string", required: false},
              {label: "Twitter", name: "twitter", widget: "string", required: false}
            ]}
      
      - label: "Homepage Content"
        name: "homepage"
        file: "_data/settings/homepage.yml"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "text"}
          - {label: "Hero Background Image", name: "hero_image", widget: "image"}
          - {label: "About Section Title", name: "about_title", widget: "string"}
          - {label: "About Section Text", name: "about_text", widget: "text"}
          - {label: "Featured Puppies Title", name: "puppies_title", widget: "string"}
          - {label: "Featured Puppies Text", name: "puppies_text", widget: "text"}