title: "Standard Parti Poodles Australia"
description: "Premium Standard Parti Poodles bred in Mansfield, Victoria. Health tested, family-raised poodle puppies from champion bloodlines."
email: "info@partipoodlesaustralia.com"
phone: "+61 XXX XXX XXX"
address: "Mansfield, Victoria, Australia"
social:
  facebook: ""
  instagram: ""
  twitter: ""